### ISSUE TITLE
Failed to obtain correct threshold 

### ISSUE THREAD

**Issue by koeic** [Turku-BioImaging/ColonyArea#1]
Hi, 

I have performed colony-forming assay using MDA-MB-231 cancer cells, which have a tendency to spread out during growth to form a monolayer, with a doubling time of around 36 hours. The assay lasted for 2 weeks and majority of the surface of the wells were occupied. The wells were then stained with crystal violet.  

I tried using the automatic "Colony thresholder" plug-in and the thresholds for some of the wells were not satisfactory.
I then tried determining the ideal threshold using "image > adjust > threshold" then apply the threshold number onto "manual thresholder". The results were better but some of the wells still do not show accurate results. 

May I know if there is a solution to this problem please? 

Picture of the original plate, results obtained using "colony thresholder" and "manual colony thresholder" are in the link:  https://drive.google.com/drive/folders/1iREyz8UjfAuXQEZB6nnDdtWwaPG2R9mU?usp=share_link

Thank you very much.

**Comment by junelsolis** [comment]
@koeic I believe that you have been in touch with one of the authors already. Have you been able to resolve this issue?

**Comment by koeic** [comment]
Dear Junel,

Indeed, I have received an email from Camilo. I tried shortening the duration of the assay, a smaller surface was covered and the analysis was able to detect the correct threshold. Thank you so much for your help.

Best regards,
Koei

**Comment by junelsolis** [comment]
Thanks for the feedback! If you have any ideas about how to make this plugin better, please do feel free to open another issue.
